profile=fast
save-position-on-quit=yes
force-seekable=yes

osd-font-size=18

sub-font=Inter Medium
sub-scale=0.9
slang=en,eng,enUS,en-US
sub-auto=fuzzy

alang=ja,jp,jpn,en,eng
audio-file-auto=fuzzy

# Using uosc and thumbfast
osc=no
osd-bar=no
border=no

volume=75 # 75% on startup.
volume-max=100 # max vol to 100%.

#Youtube videos in 360p or less.
ytdl-format=bestvideo[height<=?360]+bestaudio/best
ytdl-raw-options=ignore-config=,sub-lang="en,eng,enUS,en-US",write-sub=,write-auto-sub=,cookies-from-browser=firefox
