[mgr]
border_symbol = " "

[tabs]
# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "█", close = "█" }
